# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore Internal dependencies
      run: dotnet restore PetProject/CurrencyApi/InternalApi/InternalApi.csproj
    - name: Restore Public dependencies
      run: dotnet restore PetProject/CurrencyApi/PublicApi/PublicApi.csproj
    - name: Build Internal
      run: dotnet build PetProject/CurrencyApi/InternalApi/InternalApi.csproj --no-restore
    - name: Build Public
      run: dotnet build PetProject/CurrencyApi/PublicApi/PublicApi.csproj --no-restore
    - name: Archive artifact
      uses: actions/upload-artifact@main
      with:
        name: build-artifact
        path: PetProject/CurrencyApi/PublicApi/bin/Debug/net7.0/
    - name: Download Artifact
      uses: actions/download-artifact@main
      with:
        name: build-artifact
        path: PetProject/CurrencyApi/PublicApi/bin/Debug/net7.0/
    - name: Install FTP cmd tool
      run: sudo apt-get install ftp-upload
    - name: 📂 Deploy to FTP server
      run: ftp-upload -h web-api.somee.com -u {{ secrets.FTP_USER_NAME }} --password {{ secrets.FTP_PASSWORD }} -d ./www.web-api.somee.com/ PetProject/CurrencyApi/PublicApi/bin/Debug/net7.0
