name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
        env:
          GITHUB_ENVIRONMENT: "DotnetDefault"
        run: |
          github-env-export GITHUB_ENVIRONMENT
          gh repo update --environment $GITHUB_ENVIRONMENT
